name: DevSecOps Pipeline

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ecs-fargate-lab

jobs:

  # ------------------------
  # 1. BUILD
  # ------------------------
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116981775264:role/ecs-fargate-lab-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        id: meta
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE \
            --push ./app

          echo "image=$IMAGE" >> $GITHUB_OUTPUT

  # ------------------------
  # 2. IMAGE SCAN (Shift Left)
  # ------------------------
  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116981775264:role/ecs-fargate-lab-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Scan image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.image }}
          severity: CRITICAL,HIGH
          exit-code: 0

  # ------------------------
  # 3. DEPLOY STAGING
  # ------------------------
  deploy-staging:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - uses: actions/checkout@v4

      - name: Deploy ECS (staging)
        run: echo "Deploy to staging..."

  # ------------------------
  # 4. DAST (ZAP)
  # ------------------------
   zap-scan:
  runs-on: ubuntu-latest
  needs: deploy-staging

  steps:
    - uses: actions/checkout@v4

    - name: Fix permissions
      run: chmod -R 777 .

    - name: Wait for service
      run: sleep 60

    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: "http://ecs-fargate-lab-alb-1574663482.us-east-1.elb.amazonaws.com"
        fail_action: true

  # ------------------------
  # 5. DEPLOY PROD (GATED)
  # ------------------------
  deploy-prod:
    runs-on: ubuntu-latest
    needs: zap-scan

    steps:
      - name: Deploy ECS PROD
        run: echo "Deploy to production..."
