name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
      - feature/**

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ecs-fargate-lab
  ECS_CLUSTER: ecs-fargate-lab-cluster
  ECS_SERVICE: ecs-fargate-lab-service
  CONTAINER_NAME: ecs-fargate-lab

jobs:

# ------------------------
# 1. BUILD
# ------------------------
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116981775264:role/ecs-fargate-lab-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        id: meta
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          echo "Building image: $IMAGE"

          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE \
            --push ./app

          echo "image=$IMAGE" >> $GITHUB_OUTPUT

# ------------------------
# 2. IMAGE SCAN (REAL GATE)
# ------------------------
  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116981775264:role/ecs-fargate-lab-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Scan image (Trivy - BLOCKING)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.image }}
          severity: CRITICAL
          exit-code: 1

# ------------------------
# 3. DEPLOY (ECS REAL)
# ------------------------
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - security-scan

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116981775264:role/ecs-fargate-lab-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug image (verificación)
        run: echo "Deploying image: ${{ needs.build.outputs.image }}"

      - name: Render task definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ needs.build.outputs.image }}

      - name: Deploy ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

# ------------------------
# 4. DAST (NO BLOQUEA)
# ------------------------
  zap-scan:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Wait for service
        run: sleep 60

      - name: ZAP Scan (report only)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://ecs-fargate-lab-alb-1574663482.us-east-1.elb.amazonaws.com"
          fail_action: false
          